In [1]:
%run setup.ipynb

In [2]:
output_dir = '/home/joshjrey/Documents/mosquito_project/outputs/build_blocks'

In [3]:
tbl_features = etl.frompickle(os.path.join(output_dir, 'tbl_features.pkl.gz'))
tbl_features

+-------+--------------+--------+----------+----------+--------+-------+-----------------+-----------------+------------+-------------------+--------------+----------+---------+
| seqid | type         | start  | stop     | length   | strand | phase | parent          | ID              | n_children | transcript_length | is_canonical | is_first | is_last |
+=======+==============+========+==========+==========+========+=======+=================+=================+============+===================+==============+==========+=========+
| '2L'  | 'chromosome' |      0 | 49364325 | 49364325 | '.'    | '.'   | None            | '2L'            |          0 | None              | None         | None     | None    |
+-------+--------------+--------+----------+----------+--------+-------+-----------------+-----------------+------------+-------------------+--------------+----------+---------+
| '2L'  | 'gene'       | 157347 |   186936 |    29589 | '-'    | '.'   | None            | 'AGAP004677'    |          2 | None              | None         | None     | None    |
+-------+--------------+--------+----------+----------+--------+-------+-----------------+-----------------+------------+-------------------+--------------+----------+---------+
| '2L'  | 'mRNA'       | 157347 |   181305 |    23958 | '-'    | '.'   | 'AGAP004677'    | 'AGAP004677-RA' |         10 |              1467 | True         | None     | None    |
+-------+--------------+--------+----------+----------+--------+-------+-----------------+-----------------+------------+-------------------+--------------+----------+---------+
| '2L'  | 'mRNA'       | 157347 |   186936 |    29589 | '-'    | '.'   | 'AGAP004677'    | 'AGAP004677-RB' |         10 |              1147 | False        | None     | None    |
+-------+--------------+--------+----------+----------+--------+-------+-----------------+-----------------+------------+-------------------+--------------+----------+---------+
| '2L'  | 'exon'       | 157347 |   157623 |      276 | '-'    | '.'   | 'AGAP004677-RA' | None            |          0 | None              | True         | False    | True    |
+-------+--------------+--------+----------+----------+--------+-------+-----------------+-----------------+------------+-------------------+--------------+----------+---------+
...

In [4]:
from Bio.Data import CodonTable
standard_table = CodonTable.unambiguous_dna_by_name["Standard"]
standard_table.forward_table

{'AAA': 'K',
 'AAC': 'N',
 'AAG': 'K',
 'AAT': 'N',
 'ACA': 'T',
 'ACC': 'T',
 'ACG': 'T',
 'ACT': 'T',
 'AGA': 'R',
 'AGC': 'S',
 'AGG': 'R',
 'AGT': 'S',
 'ATA': 'I',
 'ATC': 'I',
 'ATG': 'M',
 'ATT': 'I',
 'CAA': 'Q',
 'CAC': 'H',
 'CAG': 'Q',
 'CAT': 'H',
 'CCA': 'P',
 'CCC': 'P',
 'CCG': 'P',
 'CCT': 'P',
 'CGA': 'R',
 'CGC': 'R',
 'CGG': 'R',
 'CGT': 'R',
 'CTA': 'L',
 'CTC': 'L',
 'CTG': 'L',
 'CTT': 'L',
 'GAA': 'E',
 'GAC': 'D',
 'GAG': 'E',
 'GAT': 'D',
 'GCA': 'A',
 'GCC': 'A',
 'GCG': 'A',
 'GCT': 'A',
 'GGA': 'G',
 'GGC': 'G',
 'GGG': 'G',
 'GGT': 'G',
 'GTA': 'V',
 'GTC': 'V',
 'GTG': 'V',
 'GTT': 'V',
 'TAC': 'Y',
 'TAT': 'Y',
 'TCA': 'S',
 'TCC': 'S',
 'TCG': 'S',
 'TCT': 'S',
 'TGC': 'C',
 'TGG': 'W',
 'TGT': 'C',
 'TTA': 'L',
 'TTC': 'F',
 'TTG': 'L',
 'TTT': 'F'}

In [5]:
#genome = phase2_ar1.genome_agamp3
#genome
phase2_ar1.init("/home/joshjrey/Documents/mosquito_project/data/ag1k/phase2.AR1")
genome = phase2_ar1.genome_agamp3
genome

In [14]:
genome

In [15]:
codon_degeneracy = {k: np.full(len(genome[k]), dtype='i1', fill_value=-1)
                    for k in genome.keys()}
codon_degeneracy

{'2L': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8),
 '2R': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8),
 '3L': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8),
 '3R': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8),
 'UNKN': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8),
 'X': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8),
 'Y_unplaced': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8)}

In [16]:
codon_position = {k: np.full(len(genome[k]), dtype='i1', fill_value=-1)
                  for k in genome.keys()}
codon_position

{'2L': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8),
 '2R': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8),
 '3L': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8),
 '3R': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8),
 'UNKN': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8),
 'X': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8),
 'Y_unplaced': array([-1, -1, -1, ..., -1, -1, -1], dtype=int8)}

In [17]:
codon_nonsyn = {k: np.zeros(len(genome[k]), dtype='u1')
                  for k in genome.keys()}
codon_nonsyn

{'2L': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 '2R': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 '3L': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 '3R': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'UNKN': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'X': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 'Y_unplaced': array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)}

In [18]:
ref_all = {k: np.zeros(len(genome[k]), dtype='U')
                  for k in genome.keys()}
ref_all

{'2L': array(['', '', '', ..., '', '', ''], dtype='<U1'),
 '2R': array(['', '', '', ..., '', '', ''], dtype='<U1'),
 '3L': array(['', '', '', ..., '', '', ''], dtype='<U1'),
 '3R': array(['', '', '', ..., '', '', ''], dtype='<U1'),
 'UNKN': array(['', '', '', ..., '', '', ''], dtype='<U1'),
 'X': array(['', '', '', ..., '', '', ''], dtype='<U1'),
 'Y_unplaced': array(['', '', '', ..., '', '', ''], dtype='<U1')}

In [20]:
bases = ['A', 'C', 'T', 'G']
codon_table = standard_table.forward_table.copy()
for codon in standard_table.stop_codons:
    codon_table[codon] = '*'

In [21]:
from Bio.Seq import Seq

In [22]:
for cds in tbl_features.eq('type', 'CDS').true('is_canonical').records():
#     print(cds)
    if cds.seqid not in genome:
        continue
    if cds.strand == '+':
        seq = genome[cds.seqid][cds.start:cds.stop].upper()
#         print(cds.phase, seq[:10])
        phase = int(cds.phase)
        for i in range(cds.length):
            codon_pos = (i - phase) % 3
            if codon_pos == 0:
                codon_start = i
                codon_stop = i+3
            elif codon_pos == 1:
                codon_start = i-1
                codon_stop = i+2
            elif codon_pos == 2:
                codon_start = i-2
                codon_stop = i+1
            else:
                raise RuntimeError('unexpected codon_pos', codon_pos)
            if codon_start < 0:
                continue
            if codon_stop > cds.length:
                continue
            codon = seq[codon_start:codon_stop]
            if 'N' not in codon:
                codons = None
                if codon_pos == 0:
                    codons = [b + codon[1:] for b in bases]
                elif codon_pos == 1:
                    codons = [codon[0] + b + codon[2] for b in bases]
                elif codon_pos == 2:
                    codons = [codon[:2] + b for b in bases]
                aas = [codon_table[c] for c in codons]
                # assign degeneracy
                aas_ct = collections.Counter(aas)
                if len(aas_ct) == 1:
                    # 4-fold degenerate
                    deg = 4
                elif len(aas_ct) == 4:
                    # 0-fold degenerate
                    deg = 1
                elif len(aas_ct) == 2 and tuple(aas_ct.values()) == (2, 2):
                    # simple 2-fold degenerate
                    deg = 2
                else:
                    # complex 2-fold degenerate
                    deg = 3
                # assign number of nonsyn mutations
                ref_aa = codon_table[codon]
                alt_aa = [a for a in aas if a != ref_aa]
                nonsyn = len(alt_aa)
                codon_position[cds.seqid][cds.start + i] = codon_pos
                codon_degeneracy[cds.seqid][cds.start + i] = deg
                codon_nonsyn[cds.seqid][cds.start + i] = nonsyn
                
                
#                 print(i, codon_pos, codon, codons, ref_aa, aas, deg, nonsyn)
    else:
        seq = genome[cds.seqid][cds.start:cds.stop].upper()
        seq = str(Seq(seq).reverse_complement())
#         print(cds.phase, seq[:10])
        phase = int(cds.phase)
        for i in range(cds.length):
            codon_pos = (i - phase) % 3
            if codon_pos == 0:
                codon_start = i
                codon_stop = i+3
            elif codon_pos == 1:
                codon_start = i-1
                codon_stop = i+2
            elif codon_pos == 2:
                codon_start = i-2
                codon_stop = i+1
            else:
                raise RuntimeError('unexpected codon_pos', codon_pos)
            if codon_start < 0:
                continue
            if codon_stop > cds.length:
                continue
            codon = seq[codon_start:codon_stop]
            if 'N' not in codon:
                codons = None
                if codon_pos == 0:
                    codons = [b + codon[1:] for b in bases]
                elif codon_pos == 1:
                    codons = [codon[0] + b + codon[2] for b in bases]
                elif codon_pos == 2:
                    codons = [codon[:2] + b for b in bases]
                aas = [codon_table[c] for c in codons]
                # assign degeneracy
                aas_ct = collections.Counter(aas)
                if len(aas_ct) == 1:
                    # 4-fold degenerate
                    deg = 4
                elif len(aas_ct) == 4:
                    # 0-fold degenerate
                    deg = 1
                elif len(aas_ct) == 2 and tuple(aas_ct.values()) == (2, 2):
                    # simple 2-fold degenerate
                    deg = 2
                else:
                    # complex 2-fold degenerate
                    deg = 3
                # assign number of nonsyn mutations
                ref_aa = codon_table[codon]
                alt_aa = [a for a in aas if a != ref_aa]
                nonsyn = len(alt_aa)
                seq_index = cds.stop - i - 1
                codon_position[cds.seqid][seq_index] = codon_pos
                codon_degeneracy[cds.seqid][seq_index] = deg
                codon_nonsyn[cds.seqid][seq_index] = nonsyn
            
#                 print(i, codon_pos, codon, codons, ref_aa, aas, deg, nonsyn, seq_index, genome[cds.seqid][seq_index])

In [23]:
print(np.sum(codon_nonsyn['2L']==1 )   + np.sum(codon_nonsyn['2L']==2) + np.sum(codon_nonsyn['2L']==3) )
print(np.sum(codon_degeneracy['2L']!=-1) )
print(np.sum(codon_position['2L']!=-1) )

3902104
4672719
4672719


In [24]:
unique, counts = np.unique(codon_nonsyn['2L'], return_counts=True)
list(zip(unique, counts))

[(0, 45462221), (1, 74840), (2, 812756), (3, 3014508)]

In [25]:
x = codon_position['3L']
y = codon_degeneracy['3L']
z = codon_nonsyn['3L']

In [26]:
x

array([-1, -1, -1, ..., -1, -1, -1], dtype=int8)

In [27]:
y

array([-1, -1, -1, ..., -1, -1, -1], dtype=int8)

In [28]:
np.bincount(x[x >= 0])

array([1062487, 1062488, 1062487])

In [29]:
np.bincount(y[x == 0])

array([     0, 844943,      0, 217544])

In [30]:
np.bincount(y[x == 1])

array([      0, 1050109,       0,   12379])

In [31]:
np.bincount(y[x == 2])

array([     0,      0, 431446, 111630, 519411])

In [32]:
np.bincount(z[x == 0])

array([     0,      0, 105086, 957401])

In [33]:
np.bincount(z[x == 1])

array([      0,       0,    1327, 1061161])

In [34]:
np.bincount(z[x == 2])

array([519411,  53242, 454068,  35766])

In [35]:
zarr.save_group(os.path.join(output_dir, 'codon_position.zarr.zip'), 
                **codon_position)
zarr.save_group(os.path.join(output_dir, 'codon_degeneracy.zarr.zip'), 
                **codon_degeneracy)
zarr.save_group(os.path.join(output_dir, 'codon_nonsyn.zarr.zip'), 
                **codon_nonsyn)
